### ISSUE TITLE
Allow customizing ExecStart command

### ISSUE THREAD

**Issue by mcg** [libre-ops/metabase#1]
JVM usage varies widely. Need to be able to customize JVM arguments passed into the systemd service templet for the `ExecStart`.

**Comment by Matt-Yorkley** [comment]
Sounds useful. You want to submit a PR? Maybe something like this in the service:

`{% if metabase_jvm_args is defined %}{{ metabase_jvm_args }}{% endif %}`

**Comment by mcg** [comment]
I'll cut a PR for this.

Using `{{ metabase_jvm_args | default(omit) }}` we won't have a default set in `default/main.yml` for this. Is that an issue and if so, how do you want that exposed to the user, readme or?
